# On Windows work in cmd under Admin, possible via bash
# docker build -t sdoroshenko/alpine-async-profiler .
# docker run -it --rm -v c:/Users/Sergei_Doroshenko/IdeaProjects/docker-samples/graalvm/project:/project sdoroshenko/alpine
# docker run --it -rm -v $(pwd):/project -p 8080:8080 sdoroshenko/alpine
# docker run -it --rm -v %cd%:/project -p 8080:8080 sdoroshenko/alpine-async-profiler
# docker run -it --rm sdoroshenko/alpine-async-profiler
#
# ^M is a carriage return character. Linux uses the line feed character to mark the end of a line
#
FROM alpine:latest
RUN apk update
RUN apk fetch openjdk8
RUN apk add --no-cache --upgrade bash util-linux pciutils usbutils coreutils binutils findutils grep openjdk8

COPY async-profiler-1.6-linux-x64.tar.gz /opt/
COPY target/async-profiler-test.jar /opt/
COPY *.sh /opt/

RUN chmod +x /opt/*.sh

VOLUME /project
WORKDIR /opt

EXPOSE 8080

# ------------------------------------------------------------- Grant execution permissions
#RUN apt-get update && apt-get install unzip openjdk-8-dbg -y && chmod +x /opt/*.sh

#CMD ["sh", "/opt/start.sh"]
CMD bash